### ISSUE TITLE
limit in selecting samples from CSV gene read counts

### ISSUE THREAD

**Issue by avilella** [drpowell/degust2#1]
Hi,

I tried uploading a CSV of gene read counts into degust2 with 56270 rows and 112 columns (110 samples).

The file loads correctly but when checking the boxes for the different conditions, the dropdown list cuts short at only 82, with the last one just being labeled with letter 'C'.

<img width="124" alt="screen shot 2017-04-13 at 14 15 45" src="https://cloud.githubusercontent.com/assets/158007/25006177/c8046206-2053-11e7-93ce-3908126ff510.png">

Any ideas?

**Comment by drpowell** [comment]
I have used it with that many samples, so it quite possibly has an issue.
Do you have many conditions, or many replicates?

**Comment by avilella** [comment]
Many replicates, 2-3 conditions.

**Comment by avilella** [comment]
Shortening the sample ids gets me a bit further, but still not enough.

**Comment by drpowell** [comment]
Yes, definitely a bug.  I'll try to find a fix over the weekend

**Comment by drpowell** [comment]
Should be working now
